version: "2"

services:
  client:
    build: ./client
    volumes:
      - "${WORKSPACE:-./workspace}:/usr/src/app/workspace:ro"
      - "${REPORTS:-./workspace/reports}:/usr/src/app/reports:rw"
      - "${SUITES:-./suites}:/usr/src/app/suites:ro"
    environment:
      - WORKER_PORT # allow this env var to be used in config.js
      - BALENACLOUD_API_KEY # allow this env var to be used in config.js
      - BALENACLOUD_ORG # allow this env var to be used in config.js
      - BALENACLOUD_APP_NAME # allow this env var to be used in config.js
      - DEVICE_TYPE # allow this env var to be used in config.js
      - WORKER_TYPE # allow this env var to be used in config.js
    depends_on:
      - core

  core:
    privileged: true
    build:
      context: ./core
      dockerfile: Dockerfile.template
      args:
        - BALENA_ARCH=amd64
    volumes:
      - core-storage:/data
      - reports-storage:/reports
    tmpfs:
      - /var/run
      - /var/lib/docker
    environment:
      - UDEV=1
    restart: 'no'

volumes:
  core-storage:
  reports-storage:
