version: "2"

services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.template
      args:
        - BALENA_ARCH=amd64
        - SKIP_INSTALL_BINARY=true
    device_cgroup_rules:
      # allow dynamic creation and access of qemu required misc chardev nodes
      # this includes /dev/kvm, and /dev/net/tun
      - "c 10:* rmw"
    cap_add:
      - NET_ADMIN # allow network setup
    network_mode: host
    volumes:
      - "core-storage:/data"
      - "reports-storage:/reports"
    environment:
      - UDEV=0
      - WORKER_TYPE=qemu
      - SCREEN_CAPTURE=true
      - WORKER_PORT # default 80 and must match client config.js workers

volumes:
  core-storage:
  reports-storage:
