version: '2'
services:
  core:
    privileged: true
    build: ./core
    network_mode: 'host'
  worker:
    privileged: true
    build: ./worker
    pid: 'host'
    network_mode: 'host'
    ipc: 'host'
    labels:
      io.balena.features.dbus: '1'
