on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  balena-cloud-build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleets: [testbot-rig, testbot-rig-beta, testbot-personal]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fleet: balena/${{ matrix.fleets }}
          versionbot: false
          environment: balena-cloud.com
          create_ref: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
